In [2]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [21]:
'''df = pd.read_csv('data_new_df_metadatos_bars_fl')'''

"df = pd.read_csv('data_new_df_metadatos_bars_fl')"

In [22]:
'''df'''

'df'

In [23]:
"""
Cell generated by Data Wrangler.
"""
'''def clean_data(df):
    # Round column 'latitude' (Number of decimals: 6)
    df = df.round({'latitude': 6})
    # Round column 'longitude' (Number of decimals: 6)
    df = df.round({'longitude': 6})
    return df

df = clean_data(df.copy())
df.head()'''

"def clean_data(df):\n    # Round column 'latitude' (Number of decimals: 6)\n    df = df.round({'latitude': 6})\n    # Round column 'longitude' (Number of decimals: 6)\n    df = df.round({'longitude': 6})\n    return df\n\ndf = clean_data(df.copy())\ndf.head()"

In [24]:
'''def Recomendacion(latitud, longitud):
    try:
        columnasd_interes = ['latitude', 'longitude']
        data = df[columnasd_interes]

        # Creo el modelo KNN
        knn_model = NearestNeighbors(n_neighbors=10, metric='haversine')
        knn_model.fit(data)

        # Especifico la ubicación de búsqueda
        new_lat = float(latitud)  # Se reemplaza con input
        new_long = float(longitud)  #Se reemplaza con input

        # Se consultan los 10 lugares más cercanos
        distances, indices = knn_model.kneighbors([[new_lat, new_long]])

        # Imprimo los resultados
        nearest_places = df.iloc[indices[0]].to_dict()

        return nearest_places
    except Exception as e:
        return {"error": str(e)}'''

'def Recomendacion(latitud, longitud):\n    try:\n        columnasd_interes = [\'latitude\', \'longitude\']\n        data = df[columnasd_interes]\n\n        # Creo el modelo KNN\n        knn_model = NearestNeighbors(n_neighbors=10, metric=\'haversine\')\n        knn_model.fit(data)\n\n        # Especifico la ubicación de búsqueda\n        new_lat = float(latitud)  # Se reemplaza con input\n        new_long = float(longitud)  #Se reemplaza con input\n\n        # Se consultan los 10 lugares más cercanos\n        distances, indices = knn_model.kneighbors([[new_lat, new_long]])\n\n        # Imprimo los resultados\n        nearest_places = df.iloc[indices[0]].to_dict()\n\n        return nearest_places\n    except Exception as e:\n        return {"error": str(e)}'

In [25]:
'''Recomendacion(27.974036,-82.490077)'''

'Recomendacion(27.974036,-82.490077)'

In [26]:
'''df.to_csv('data_new_df_metadatos_bars_fl.csv', index=False)'''

"df.to_csv('data_new_df_metadatos_bars_fl.csv', index=False)"

In [27]:
'''df'''

'df'

In [28]:
'''latitud = 27.974036
longitud = -82.490077


columnasd_interes = ['latitude', 'longitude']
data = df[columnasd_interes]

# Creo el modelo KNN
knn_model = NearestNeighbors(n_neighbors=10, metric='haversine')
knn_model.fit(data)

# Especifico la ubicación de búsqueda
new_lat = float(latitud)  # Se reemplaza con input
new_long = float(longitud)  #Se reemplaza con input

# Se consultan los 10 lugares más cercanos
distances, indices = knn_model.kneighbors([[new_lat, new_long]])

# Imprimo los resultados
nearest_places = df.iloc[indices[0]][['name','avg_rating','address','latitude','longitude']]

nearest_places.to_dict(orient='index')'''

"latitud = 27.974036\nlongitud = -82.490077\n\n\ncolumnasd_interes = ['latitude', 'longitude']\ndata = df[columnasd_interes]\n\n# Creo el modelo KNN\nknn_model = NearestNeighbors(n_neighbors=10, metric='haversine')\nknn_model.fit(data)\n\n# Especifico la ubicación de búsqueda\nnew_lat = float(latitud)  # Se reemplaza con input\nnew_long = float(longitud)  #Se reemplaza con input\n\n# Se consultan los 10 lugares más cercanos\ndistances, indices = knn_model.kneighbors([[new_lat, new_long]])\n\n# Imprimo los resultados\nnearest_places = df.iloc[indices[0]][['name','avg_rating','address','latitude','longitude']]\n\nnearest_places.to_dict(orient='index')"

In [29]:
'''from google.cloud import storage
import os
import gcsfs
'''

In [30]:

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "gs://datahouse-pf/pfdatahenry-3e35bd50cfeb.json"

In [31]:
'''import pandas as pd
from google.cloud import storage 
import io
import os
import gcsfs'''

In [32]:
'''os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "gs://datahouse-pf/pfdatahenry-3e35bd50cfeb.json"'''

In [35]:
'''gcs_path = 'https://storage.cloud.google.com/datahouse-pf/data/new/df_metadatos_bars_fl''''

In [36]:
'''
df1 = pd.read_csv(gcs_path)
df1'''

ParserError: Error tokenizing data. C error: Expected 334 fields in line 3, saw 345

In [3]:
df = pd.read_csv('data_new_df_metadatos_bars_fl')
df

,Unnamed: 0,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,16968,Mainstay Tavern,"Mainstay Tavern, Clearwater, FL 33767",0x88c2f730debd585f:0xeb36db3a693c980f,NaN,27.956012,-82.829346,['Restaurant'],3.5,14,NaN,"[array(['Wednesday', '4–11PM'], dtype=object)\...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 4PM,['0x88c2f730ddce0653:0xb28477eceda35923'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
1,24116,Edible Arrangements,"Edible Arrangements, 14535 S Military Trail, D...",0x88d92023dcdc9d4b:0xbca508bb3abc0a87,Chain selling clever arrangements & gift baske...,26.460622,-80.124503,['Gift shop' 'Caterer' 'Chocolate shop' 'Desse...,4.2,38,NaN,"[array(['Tuesday', '9AM–5PM'], dtype=object)\n...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 9AM Wed,['0x88d91fd31b75ddc3:0xb8b93affa70f0689'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
2,43541,Mainstay Tavern,"Mainstay Tavern, Clearwater, FL 33767",0x88c2f730debd585f:0xeb36db3a693c980f,NaN,27.956012,-82.829346,['Restaurant'],3.5,14,NaN,"[array(['Wednesday', '4–11PM'], dtype=object)\...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 4PM,['0x88c2f730ddce0653:0xb28477eceda35923'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
3,50689,Edible Arrangements,"Edible Arrangements, 14535 S Military Trail, D...",0x88d92023dcdc9d4b:0xbca508bb3abc0a87,Chain selling clever arrangements & gift baske...,26.460622,-80.124503,['Gift shop' 'Caterer' 'Chocolate shop' 'Desse...,4.2,38,NaN,"[array(['Tuesday', '9AM–5PM'], dtype=object)\n...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 9AM Wed,['0x88d91fd31b75ddc3:0xb8b93affa70f0689'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
4,90883,Del Frisco's Grille,"Del Frisco's Grille, 340 Royal Poinciana Way #...",0x88d8d69ac8872eed:0x27b6361453f3fee4,"Sophisticated chophouse chain serving steak, s...",26.717357,-80.041597,['American restaurant' 'Bar' 'Seafood restaura...,5.0,8,NaN,"[array(['Monday', '5–9PM'], dtype=object)\n ar...",{'Accessibility': array(['Wheelchair accessibl...,Permanently closed,['0x88d8d69099677c8f:0x627b734297eb3794'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,3010935,The Office,"The Office, 1107 W Florida Ave, Hemet, CA 92543",0x80db6f57ac4db905:0x20b49e74acaaa284,NaN,33.747270,-116.982863,['Bar & grill' 'Bar' 'Karaoke bar' 'Sports bar'],4.1,298,$,"[array(['Monday', '7AM–2AM'], dtype=object)\n ...",{'Accessibility': array(['Wheelchair accessibl...,Open ⋅ Closes 2AM,['0x80db65e2368b6763:0xff286f6331d1d756'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
441,3012053,Nature's Table,"Nature's Table, 2701 N Rocky Point Dr, Tampa, ...",0x88c2e9d15fb99039:0xcaaaa485ef013ebb,Counter-serve chain that offers health-oriente...,27.964112,-82.568373,['American restaurant' 'Health food restaurant...,4.5,32,$,"[array(['Monday', '7:30AM–3PM'], dtype=object)...",{'Accessibility': array(['Wheelchair accessibl...,Open ⋅ Closes 3PM,['0x88c2e9d233e10c5d:0x5c58e27486cdbe03'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
442,3016246,Muscle Maker Grill,"Muscle Maker Grill, 230 S Federal Hwy, Deerfie...",0x88d8e27dca7fd465:0x7cfcc60329194737,Branch of a counter-serve chain catering to he...,26.314856,-80.088966,['Health food restaurant' 'American restaurant...,3.9,134,$$,"[array(['Monday', '11AM–6PM'], dtype=object)\n...","{'Accessibility': None, 'Activities': None, 'A...",Permanently closed,['0x88d8e27c6d079fb3:0x4a1c34a200f807fc'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
443,3017649,The Brass Tap,"The Brass Tap, 37916 Pasco Ave, Dade City, FL ...",0x88dd54996e6ee837:0x8c3ac0230af2cb47,Festive pub with a patio offering myriad beer ...,28.363591,-82.188846,['Bar'],4.4,233,$$,"[array(['Monday', 'Closed'], dtype=object)\n a...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 1PM Tue,['0x88c2b0d7a6d30761:0x9262dae57747c028'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
444,3023137,Jamba Juice,"Jamba Juice, 430 Duval St, Key West, FL 33040",0x88d1b6e978b8744f:0xc915ac6ba2b129ed,Straightforward counter-serve chain for smooth...,24.556100,-81.803130,['Juice shop' 'Restaurant'],3.9,18,$,NaN,{'Accessibility': array(['Wheelchair accessibl...,NaN,['0x88d1b148d457aa35:0x45a12a62d7595520'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...

In [5]:
df_filtrado = df[df['avg_rating']>3.5]
df_filtrado

,Unnamed: 0,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
1,24116,Edible Arrangements,"Edible Arrangements, 14535 S Military Trail, D...",0x88d92023dcdc9d4b:0xbca508bb3abc0a87,Chain selling clever arrangements & gift baske...,26.460622,-80.124503,['Gift shop' 'Caterer' 'Chocolate shop' 'Desse...,4.2,38,NaN,"[array(['Tuesday', '9AM–5PM'], dtype=object)\n...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 9AM Wed,['0x88d91fd31b75ddc3:0xb8b93affa70f0689'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
3,50689,Edible Arrangements,"Edible Arrangements, 14535 S Military Trail, D...",0x88d92023dcdc9d4b:0xbca508bb3abc0a87,Chain selling clever arrangements & gift baske...,26.460622,-80.124503,['Gift shop' 'Caterer' 'Chocolate shop' 'Desse...,4.2,38,NaN,"[array(['Tuesday', '9AM–5PM'], dtype=object)\n...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 9AM Wed,['0x88d91fd31b75ddc3:0xb8b93affa70f0689'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
4,90883,Del Frisco's Grille,"Del Frisco's Grille, 340 Royal Poinciana Way #...",0x88d8d69ac8872eed:0x27b6361453f3fee4,"Sophisticated chophouse chain serving steak, s...",26.717357,-80.041597,['American restaurant' 'Bar' 'Seafood restaura...,5.0,8,NaN,"[array(['Monday', '5–9PM'], dtype=object)\n ar...",{'Accessibility': array(['Wheelchair accessibl...,Permanently closed,['0x88d8d69099677c8f:0x627b734297eb3794'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
5,175421,Sakura Japanese Restaurant,"Sakura Japanese Restaurant, 2785 NW 49th Ave, ...",0x88e62a97192e9417:0x28182fedc6f763b0,NaN,29.216060,-82.200803,['Japanese restaurant'],5.0,3,NaN,"[array(['Wednesday', '11AM–10PM'], dtype=objec...",{'Accessibility': array(['Wheelchair accessibl...,Permanently closed,['0x88e62d2761c0506f:0x4affe51313a6426d'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
6,182218,The Saint,"The Saint, 49 24th St N, St. Petersburg, FL 33713",0x88c2e3f3542de453:0xf2c89170626afda8,NaN,27.771392,-82.665693,['Bar'],3.7,15,NaN,"[array(['Wednesday', '5PM–12AM'], dtype=object...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 5PM,NaN,https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,3010935,The Office,"The Office, 1107 W Florida Ave, Hemet, CA 92543",0x80db6f57ac4db905:0x20b49e74acaaa284,NaN,33.747270,-116.982863,['Bar & grill' 'Bar' 'Karaoke bar' 'Sports bar'],4.1,298,$,"[array(['Monday', '7AM–2AM'], dtype=object)\n ...",{'Accessibility': array(['Wheelchair accessibl...,Open ⋅ Closes 2AM,['0x80db65e2368b6763:0xff286f6331d1d756'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
441,3012053,Nature's Table,"Nature's Table, 2701 N Rocky Point Dr, Tampa, ...",0x88c2e9d15fb99039:0xcaaaa485ef013ebb,Counter-serve chain that offers health-oriente...,27.964112,-82.568373,['American restaurant' 'Health food restaurant...,4.5,32,$,"[array(['Monday', '7:30AM–3PM'], dtype=object)...",{'Accessibility': array(['Wheelchair accessibl...,Open ⋅ Closes 3PM,['0x88c2e9d233e10c5d:0x5c58e27486cdbe03'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
442,3016246,Muscle Maker Grill,"Muscle Maker Grill, 230 S Federal Hwy, Deerfie...",0x88d8e27dca7fd465:0x7cfcc60329194737,Branch of a counter-serve chain catering to he...,26.314856,-80.088966,['Health food restaurant' 'American restaurant...,3.9,134,$$,"[array(['Monday', '11AM–6PM'], dtype=object)\n...","{'Accessibility': None, 'Activities': None, 'A...",Permanently closed,['0x88d8e27c6d079fb3:0x4a1c34a200f807fc'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
443,3017649,The Brass Tap,"The Brass Tap, 37916 Pasco Ave, Dade City, FL ...",0x88dd54996e6ee837:0x8c3ac0230af2cb47,Festive pub with a patio offering myriad beer ...,28.363591,-82.188846,['Bar'],4.4,233,$$,"[array(['Monday', 'Closed'], dtype=object)\n a...",{'Accessibility': array(['Wheelchair accessibl...,Closed ⋅ Opens 1PM Tue,['0x88c2b0d7a6d30761:0x9262dae57747c028'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...
444,3023137,Jamba Juice,"Jamba Juice, 430 Duval St, Key West, FL 33040",0x88d1b6e978b8744f:0xc915ac6ba2b129ed,Straightforward counter-serve chain for smooth...,24.556100,-81.803130,['Juice shop' 'Restaurant'],3.9,18,$,NaN,{'Accessibility': array(['Wheelchair accessibl...,NaN,['0x88d1b148d457aa35:0x45a12a62d7595520'\n '0x...,https://www.google.com/maps/place//data=!4m2!3...